# -*- coding: utf-8 -*-
"""analise_exploratoria_dados_segurança_publica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xU-OAhFkAFsCHdV1rkite1zJq7KqD_rW
"""

import pandas as pd
import chardet

with open('ocorrencias.csv', 'rb') as f:
    result = chardet.detect(f.read())

"""#Dataset Ocorrencias"""

ocorrencias = pd.read_csv("ocorrencias.csv",
                            sep=';',
                            encoding=result['encoding']
                          )
ocorrencias.head()

ocorrencias.shape

ocorrencias.columns

"""#Dataset IDH Br"""

idh_table = pd.read_csv("ipeadata.csv", sep=';')
idh_table.head()

idh_table.shape

idh_table.columns

"""#Indicador crimes SP"""

indicador_crimes_sp = pd.read_csv('indicador_municipios_sp.csv', sep=";")
indicador_crimes_sp.head()

indicador_crimes_sp.shape

indicador_crimes_sp.columns = ['cod_ibge', 'municipio', 'estado', 'regiao', 'mes/ano', 'vitimas']
indicador_crimes_sp.head()

"""#Analisando Vitimas por mês/ano"""

media_vitimas_mes_ano = indicador_crimes_sp.groupby('mes/ano').mean().vitimas
media_vitimas_mes_ano.head()

media_vitimas_mes_ano.plot(kind='hist')

"""#Analisando Tipificação crimes brasil"""

tipificacao_crime = pd.read_csv('tipificacao_crimes_brasil.csv', sep=";")
tipificacao_crime.columns = ['estado', 'tipo_crime', 'ano', 'mes', 'sexo', 'vitimas']
tipificacao_crime.head()

tipificacao_crime.tipo_crime.unique

frequencia = pd.crosstab(tipificacao_crime.tipo_crime, tipificacao_crime.ano)
frequencia

media_vitimas_mes = tipificacao_crime.groupby('mes').mean().vitimas
media_vitimas_mes

frequencia.plot(kind='hist')

indicador_crimes_sp.head()

"""## Analise das 10 cidades com mais vitimas em SP agrupadas nos anos e meses."""

from matplotlib import pyplot as plt

top_10_cidades = indicador_crimes_sp.sort_values(by='vitimas', ascending=False)
top_10_cidades_por_municipios = top_10_cidades.groupby('municipio')

top_10_cidades = top_10_cidades_por_municipios.head(10)
# top_10_cidades.head(10)

df_agrupado = top_10_cidades.groupby('municipio').agg({'vitimas': 'sum'}).reset_index()
df_agrupado = df_agrupado.sort_values(by='vitimas', ascending=False)
df_agrupado.head()

plt.barh(df_agrupado.head(10).municipio, df_agrupado.head(10).vitimas)

produtividade_policial = pd.read_csv('produtividade_policial_sp_novo.csv', sep=';')
# pd.set_option('display.float_format', '{:.0f}'.format)
produtividade_policial.head()

trns_prod_policial = produtividade_policial.T.iloc[:, 1:]
trns_prod_policial.head()

for column in trns_prod_policial.columns:
    trns_prod_policial[column] = pd.to_numeric(trns_prod_policial[column], errors='coerce')

trns_prod_policial.plot()

